version: "3.8"
services:
  back:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/docker_db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "library/postgres:11.9-alpine"
    ports:
      - "5432:5432"
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: docker_db
      PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  sample_db: